### ISSUE TITLE
Error while performing the Test Run via singularity

### ISSUE THREAD

**Issue by PraveenOraon** [DrosophilaGenomeEvolution/TrEMOLO#10]
Hi, tool looks promising in exploring TE thanks for developing.
I  was trying to do test run using:
`singularity exec  TrEMOLO.simg snakemake --snakefile TrEMOLO/run.snk --configfile TrEMOLO/test/tmp_config.yml` 
I got an error 
GET TE INSERTION...
[/home/TrEMOLO/lib/python/parse_blast_main.py] : PREFIX OUTPUT : INS_TREMOLO
BYE !
AN ERROR OCCURRED
 
[SNK INFO] ERROR PIPELINE; snakefile used : work_test/SNAKE_USED/Snakefile_outsider.snk
    Check LOG   : work_test/log/Snakefile_outsider.log
    Check ERROR : work_test/log/Snakefile_outsider.err
/usr/bin/bash: line 176: kill: (4067681) - No such process

I was not able to figure it out the problem which is causing this. 

Thanks,
Praveen

**Comment by M-D75** [comment]
Hi,

The problem seems to come from the new version of the python library `pandas` (2.0.2), this new version is not compatible with the pipeline.

The singularity container is programmed to install the appropriate version of pandas depending on the version of python3 installed. The new version of pandas (2.0.2) released on **29 May** is now chosen by default, we will correct this to force one of the compatible versions.

For the time being, I recommend that you download a singularity container [here](https://filesender.renater.fr/?s=download&token=13f3df69-9390-4f3c-b52f-f7b2306b4e82) that has already been built and contains the correct versions of the various libraries and compatible tools.

Thanks for your feedback,
M-D

**Comment by M-D75** [comment]
Or you can change in the `Singularity` file

```bash
#Python libs
python3 -m pip install biopython pandas numpy==1.21.2 matplotlib svim==1.4.2 intervaltree scipy pysam
```

with this

```bash
#Python libs
python3 -m pip install biopython pandas==1.5.3 numpy==1.21.2 matplotlib svim==1.4.2 intervaltree scipy pysam
```

Hopefully there are no other packages that are not compatible with the new update.

M-D

**Comment by PraveenOraon** [comment]
Hi,
Thank you, I greatly appreciate the time and effort you dedicated to addressing my issue.
I tried both the solutions suggested by you and both worked fine. Resulted into completion of test run successfully with zero error.

Warm Regards,
Praveen

**Comment by M-D75** [comment]
Hi,

Thank you for your feedback. Don't hesitate to report other problems.

Following your feedback the `TrEMOLO/Singularity` file has been updated.

Thanks
M-D
