### ISSUE TITLE
`[SNK INFO] ERROR PIPELINE` while doing test run

### ISSUE THREAD

**Issue by clemgoub** [DrosophilaGenomeEvolution/TrEMOLO#4]
Hello!

I am encountering some errors while performing the test run for TrEMOLO, as described in the README. I built a singularity container following the documentation and everything seemed to go smoothly. 

When I execute this command:

```
singularity exec TrEMOLO.simg snakemake --snakefile TrEMOLO/run.snk --configfile TrEMOLO/test/tmp_config.yml
```

I end up with these errors:

```
GET SV WITH Assemblytics with alignment...
AN ERROR OCCURRED

[SNK INFO] ERROR PIPELINE; snakefile used : work_test/SNAKE_USED/Snakefile_insider.snk

snake log file : work_test/log/Snakefile_insider.log
 Error file : work_test/log/Snakefile_insider.err
```

and later

```
GET INSERTION...
AN ERROR OCCURRED

[SNK INFO] ERROR PIPELINE; snakefile used : work_test/SNAKE_USED/Snakefile_outsider.snk
    Check LOG   : work_test/log/Snakefile_outsider.log
    Check ERROR : work_test/log/Snakefile_outsider.err
/usr/bin/bash: line 169: kill: (88322) - No such process
```

I have attached the full log, as well as the snakemake files and .log/.err associated to them [TrEMOLO_logs.tar.gz](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/files/10925963/TrEMOLO_logs.tar.gz). 

Please let me know if you need further info. I have built the image on a ubuntu system with sudo, and transferred the image to our HPC. 
- I tried the test run both on a compute or login nodes, without success. 
- I've also added `MODE_PARALLELING: True` that was missing in the test config file but with no effect on the issue.
- I verified that the test data are in a disk that is mounted in singularity (`~/TrEMOLO`)

Thanks a a lot for your help!

Clément

**Comment by M-D75** [comment]
Hello,

I would need more information, could you provide me with the other log files such as `work_test/log/SV_INSIDER.err`, `work_test/log/sniffles.err`.

The `MODE_PARALLELING` is currently unstable, an update is in progress, I advise you to set it to `False`. Thanks for specifying that it was missing from the file in the test config file.

I would also like to see the output file `work_test/INSIDER/VARIANT_CALLING/pm_against_ref.sam.delta`. But to do this you will first need to modify the `TrEMOLO/run.snk` file at line **303** to add the `--keep-incomplete` option (useful to keep the output files during an error) like this

```
snakemake --keep-incomplete --snakefile ${{path_to_pipline}}/Snakefile --configfile {params.name_configfil} ...
```

and then restart the pipeline.

Please before sending me the log files, and restarting the pipeline, delete the `work_test` folder in order to have complete information in the log files.

What version of singularity is used to build the container and run it on the compute nodes ?

Have you tried running the test on your local PC (it doesn't take much time or resources) ?

Thanks for your feedback,
Mourdas

**Comment by clemgoub** [comment]
Hello Moudras! 

Thanks for your answer, I will try that today and send you all the required files. I built the image with `singularity-ce version 3.10.2-jammy` on a Ubuntu system. I execute it on our HPC (https://docs.alliancecan.ca/wiki/Technical_documentation).

I will also try on my local PC, which I didn't, thanks for the advice!

More to come,

Clém

**Comment by clemgoub** [comment]
Hi gain, I've followed your instructions and re-run the tests.

- The main log is here: [TrEMOLO.test.031323.log](https://github.com/DrosophilaGenomeEvolution/TrEMOLO/files/10960759/TrEMOLO.test.031323.log)

- I finally wrapped all the outputs in this archive: https://drive.google.com/file/d/1BnaWKy1k8kyg0ROanjrz1pdZQh-yIK8X/view?usp=sharing (I hope there is everything you need).

In addition, the version on Singularity on the HPC is `singularity version 3.8.7-1.el7` (so older than the one I used to build). Will now try on my PC (I'll try on the ubuntu VM I run on my Mac).

**Comment by clemgoub** [comment]
UPDATE: it worked on my laptop's VM without issues (by the way, I love the html report, it's very neat!). I'm looking forward to your expertise for the failed run on HPC. I will try to match the singularity versions to see if it caused the error.

Cheers,

Clém

**Comment by M-D75** [comment]
You are right, I think the problem is the mounting of the home in the container. Excellent idea the `--contain` option but I think it's too strict I suggest you use the `--no-home` option instead example :

```
singularity exec -B /home/cgoubert/bin/ --no-home TrEMOLO.simg snakemake --snakefile TrEMOLO/run.snk --configfile TrEMOLO/test/tmp_config.yml
```

I think that should solve the problem.

don't worry about the version of **singularity**, I have version 3.6.0 on HPC and its working.

thanks about the "**report.html**" feedback it's just the beginning :smile: 

Cordialy,
Mourdas

**Comment by M-D75** [comment]
After reflection this will not help you any further.

I may have an idea, I'll do some tests and get back to you, if it works

**Comment by clemgoub** [comment]
That was it! Thanks a bunch, it passed all the tests!

Cheers,

Clément
